---
settings:
  name: NetApp Solutions SAP
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: it-it,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,es-es,fr-fr
sidebar:
  entries:
  - title: Soluzioni SAP
    url: "/index.html"
  - section: bp
  - section: backup
  - section: lifecycle
  - section: briefs
  - title: Soluzioni SAP FlexPod
    url: https://docs.netapp.com/us-en/flexpod/ent-db/index.html
  - title: Soluzioni NetApp
    url: https://docs.netapp.com/us-en/netapp-solutions/
  - title: Note legali
    url: "/reference_legal_notices.html"
