---
settings:
  name: NetApp Solutions SAP
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: it-it,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,es-es,fr-fr
sidebar:
  entries:
  - title: Soluzioni SAP
    url: "/index.html"
  - section: bp
  - section: backup
  - section: lifecycle
  - section: briefs
  - title: Soluzioni SAP FlexPod
    url: https://docs.netapp.com/us-en/flexpod/ent-db/index.html
  - title: Soluzioni NetApp
    url: https://docs.netapp.com/us-en/netapp-solutions/
  - title: Note legali
    url: "/reference_legal_notices.html"
homepage:
  tiles:
  - title: Best practice per la configurazione
    links:
    - title: Video e demo
      url: sap-bp-videos.html
    - title: Blog
      url: sap-bp-blogs.html
    - title: Strumenti
      url: sap-bp-tools.html
  - title: Backup, ripristino e disaster recovery
    links:
    - title: Video e demo
      url: sap-dr-videos.html
    - title: Blog
      url: sap-dr-blogs.html
    - title: Strumenti
      url: sap-dr-tools.html
  - title: Gestione del ciclo di vita
    links:
    - title: Video e demo
      url: sap-lcm-videos.html
    - title: Blog
      url: sap-lcm-blogs.html
    - title: Strumenti
      url: sap-lcm-tools.html
  - title: Tutte le soluzioni SAP
    links:
    - title: Novità
      url: sap-whatsnew.html
    - title: Video e demo
      url: sap-videos.html
    - title: Blog
      url: sap-blogs.html
