---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'netapp, solutions, sap, sap hana, what"s new, updates, change log' 
summary: Registro delle modifiche recenti apportate alle soluzioni NetApp per i materiali collaterali SAP. 
---
= Novità nelle soluzioni NetApp per SAP
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Scopri le novità nelle soluzioni per SAP.



== 02 dicembre 2025

Nuova soluzione:link:https://docs.netapp.com/us-en/netapp-solutions-sap/backup/hana-sc-generic-scope.html["Backup e recovery SAP HANA con SnapCenter"^]

Questa soluzione fornisce le best practice per la protezione dei dati SAP HANA con NetApp SnapCenter, coprendo le linee guida di configurazione e funzionamento SnapCenter per la protezione dei sistemi SAP HANA sui sistemi ONTAP AFF e ASA , Azure NetApp Files e Amazon FSx per ONTAP.



== 12 novembre 2025

Nuova soluzionelink:https://docs.netapp.com/us-en/netapp-solutions-sap/bp/kvm-hana-introduction.html["SAP HANA con SUSE KVM e NetApp Storage"^] :

Distribuisci SAP HANA Single-Host su SUSE KVM utilizzando lo storage NetApp con interfacce di rete SR-IOV e accesso allo storage NFS o FCP.



== 18 agosto 2025

Il sito NetApp Solutions è ora illink:https://docs.netapp.com/us-en/netapp-solutions-family/index.html["Famiglia di soluzioni NetApp"^] , che comprende i seguenti siti:

* link:https://docs.netapp.com/us-en/netapp-solutions-ai/index.html["Soluzioni di intelligenza artificiale NetApp"^]
* link:https://docs.netapp.com/us-en/netapp-solutions-containers/index.html["Soluzioni container NetApp"^]
* link:https://docs.netapp.com/us-en/netapp-solutions-dataops/index.html["Soluzioni di gestione dei dati NetApp"^]
* link:https://docs.netapp.com/us-en/netapp-solutions-databases/index.html["Soluzioni di database NetApp"^]
* link:https://docs.netapp.com/us-en/netapp-solutions-cloud/index.html["Soluzioni cloud pubbliche e ibride NetApp"^]
* Soluzioni NetApp per SAP
* link:https://docs.netapp.com/us-en/netapp-solutions-virtualization/index.html["Soluzioni di virtualizzazione NetApp"^]

