---
sidebar: sidebar 
permalink: backup/fsxn-configure-replication-relationships.html 
keywords: Peer FSx, ontap file system, svm, target volume, snapmirror, 
summary: Questa sezione descrive come eseguire il peer di file system FSX per ONTAP, peer di SVM, creare un volume di destinazione, creare una policy SnapMirror, creare una relazione SnapMirror e inizializzare SnapMirror. 
---
= Configurare le relazioni di replica su FSX per i file system ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Per ulteriori informazioni sulle opzioni di configurazione di SnapMirror, consultare la documentazione di ONTAP all'indirizzo https://docs.netapp.com/us-en/ontap/data-protection/snapmirror-replication-workflow-concept.html["Workflow di replica di SnapMirror (netapp.com)"^].

* FSX di origine per il file system ONTAP: `FsxId00fa9e3c784b6abbb`
* SVM di origine: `sapcc-hana-svm`
* FSX di destinazione per il file system ONTAP: `FsxId05f7f00af49dc7a3e`
* SVM di destinazione: `sapcc-backup-target-zone5`




== Peer FSX per file system ONTAP

....
FsxId00fa9e3c784b6abbb::> network interface show -role intercluster
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
FsxId00fa9e3c784b6abbb
            inter_1      up/up    10.1.1.57/24       FsxId00fa9e3c784b6abbb-01
                                                                   e0e     true
            inter_2      up/up    10.1.2.7/24        FsxId00fa9e3c784b6abbb-02
                                                                   e0e     true
2 entries were displayed.
....
....
FsxId05f7f00af49dc7a3e::> network interface show -role intercluster
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
FsxId05f7f00af49dc7a3e
            inter_1      up/up    10.1.2.144/24      FsxId05f7f00af49dc7a3e-01
                                                                   e0e     true
            inter_2      up/up    10.1.2.69/24       FsxId05f7f00af49dc7a3e-02
                                                                   e0e     true
2 entries were displayed.
....
....
FsxId05f7f00af49dc7a3e::> cluster peer create -address-family ipv4 -peer-addrs 10.1.1.57, 10.1.2.7
Notice: Use a generated passphrase or choose a passphrase of 8 or more characters. To ensure the authenticity of the peering relationship, use a phrase or sequence of characters that would be hard to guess.
Enter the passphrase:
Confirm the passphrase:
Notice: Now use the same passphrase in the "cluster peer create" command in the other cluster.
....

NOTE: `peer-addrs` Sono gli IP del cluster di destinazione.

....
FsxId00fa9e3c784b6abbb::>  cluster peer create -address-family ipv4 -peer-addrs  10.1.2.144, 10.1.2.69
Notice: Use a generated passphrase or choose a passphrase of 8 or more characters. To ensure the authenticity of the peering relationship, use a
        phrase or sequence of characters that would be hard to guess.
Enter the passphrase:
Confirm the passphrase:
FsxId00fa9e3c784b6abbb::>
FsxId00fa9e3c784b6abbb::> cluster peer show
Peer Cluster Name         Cluster Serial Number Availability   Authentication
------------------------- --------------------- -------------- --------------
FsxId05f7f00af49dc7a3e    1-80-000011           Available      ok
....


== SVM peer

....
FsxId05f7f00af49dc7a3e::> vserver peer create -vserver sapcc-backup-target-zone5 -peer-vserver sapcc-hana-svm -peer-cluster FsxId00fa9e3c784b6abbb -applications snapmirror
Info: [Job 41] 'vserver peer create' job queued
....
....
FsxId00fa9e3c784b6abbb::> vserver peer accept -vserver sapcc-hana-svm  -peer-vserver sapcc-backup-target-zone5
Info: [Job 960] 'vserver peer accept' job queued
....
....
FsxId05f7f00af49dc7a3e::> vserver peer show
            Peer        Peer                           Peering        Remote
Vserver     Vserver     State        Peer Cluster      Applications   Vserver
----------- ----------- ------------ ----------------- -------------- ---------
sapcc-backup-target-zone5
            peer-source-cluster
                        peered       FsxId00fa9e3c784b6abbb
                                                       snapmirror     sapcc-hana-svm
....


== Creare un volume di destinazione

È necessario creare il volume di destinazione con il tipo `DP` per contrassegnarlo come destinazione di replica.

....
FsxId05f7f00af49dc7a3e::> volume create -vserver sapcc-backup-target-zone5  -volume PFX_data_mnt00001 -aggregate aggr1 -size 100GB -state online -policy default -type DP -autosize-mode grow_shrink -snapshot-policy none -foreground true -tiering-policy all -anti-ransomware-state disabled
[Job 42] Job succeeded: Successful
....


== Creare un criterio SnapMirror

Il criterio SnapMirror e la regola aggiunta definiscono la conservazione e l'etichetta SnapMirror per identificare le istantanee da replicare. Quando si crea il criterio SnapCenter in un secondo momento, è necessario utilizzare la stessa etichetta.

....
FsxId05f7f00af49dc7a3e::> snapmirror policy create -policy snapcenter-policy -tries 8 -transfer-priority normal -ignore-atime false -restart always -type vault -vserver sapcc-backup-target-zone5
....
....
FsxId05f7f00af49dc7a3e::> snapmirror policy add-rule -vserver sapcc-backup-target-zone5  -policy snapcenter-policy -snapmirror-label snapcenter -keep 14
....
....
FsxId00fa9e3c784b6abbb::> snapmirror policy showVserver Policy             Policy Number         Transfer
Name    Name               Type   Of Rules Tries Priority Comment
------- ------------------ ------ -------- ----- -------- ----------
FsxId00fa9e3c784b6abbb
        snapcenter-policy  vault         1     8  normal  -
  SnapMirror Label: snapcenter                         Keep:      14
                                                 Total Keep:      14
....


== Creare una relazione SnapMirror

Ora viene definita la relazione tra il volume di origine e quello di destinazione, oltre al tipo XDP e alla policy creata in precedenza.

....
FsxId05f7f00af49dc7a3e::> snapmirror create -source-path sapcc-hana-svm:PFX_data_mnt00001 -destination-path sapcc-backup-target-zone5:PFX_data_mnt00001 -vserver sapcc-backup-target-zone5 -throttle unlimited -identity-preserve false -type XDP -policy snapcenter-policy
Operation succeeded: snapmirror create for the relationship with destination "sapcc-backup-target-zone5:PFX_data_mnt00001".
....


== Inizializzare SnapMirror

Con questo comando, viene avviata la replica iniziale. Si tratta di un trasferimento completo di tutti i dati dal volume di origine al volume di destinazione.

....
FsxId05f7f00af49dc7a3e::> snapmirror initialize -destination-path sapcc-backup-target-zone5:PFX_data_mnt00001 -source-path sapcc-hana-svm:PFX_data_mnt00001
Operation is queued: snapmirror initialize of destination "sapcc-backup-target-zone5:PFX_data_mnt00001".
....
È possibile controllare lo stato della replica con `snapmirror show` comando.

....
FsxId05f7f00af49dc7a3e::> snapmirror show
                                                                       Progress
Source            Destination Mirror  Relationship   Total             Last
Path        Type  Path        State   Status         Progress  Healthy Updated
----------- ---- ------------ ------- -------------- --------- ------- --------
sapcc-hana-svm:PFX_data_mnt00001
            XDP  sapcc-backup-target-zone5:PFX_data_mnt00001
                              Uninitialized
                                      Transferring   1009MB    true    02/24 12:34:28
....
....
FsxId05f7f00af49dc7a3e::> snapmirror show
                                                                       Progress
Source            Destination Mirror  Relationship   Total             Last
Path        Type  Path        State   Status         Progress  Healthy Updated
----------- ---- ------------ ------- -------------- --------- ------- --------
sapcc-hana-svm:PFX_data_mnt00001
            XDP  sapcc-backup-target-zone5:PFX_data_mnt00001
                              Snapmirrored
                                      Idle           -         true    -
....