---
sidebar: sidebar 
permalink: backup/fsxn-additional-info.html 
keywords:  
summary:  
---
= Dove trovare ulteriori informazioni
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Per ulteriori informazioni sulle informazioni descritte in questo documento, consultare i seguenti documenti e/o siti Web:

* Guida utente di FSX per NetApp ONTAP - che cos'è Amazon FSX per NetApp ONTAP?
+
https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/what-is-fsx-ontap.html[]

* Pagina delle risorse SnapCenter
+
https://www.netapp.com/us/documentation/snapcenter-software.aspx["https://www.netapp.com/us/documentation/snapcenter-software.aspx"]

* Documentazione del software SnapCenter
+
https://docs.netapp.com/us-en/snapcenter/index.html["https://docs.netapp.com/us-en/snapcenter/index.html"]

* TR-4667: Automazione delle operazioni di copia e clonazione del sistema SAP HANA con SnapCenter
+
link:../lifecycle/sc-copy-clone-introduction.html["Automazione delle operazioni di copia e clonazione del sistema SAP HANA con SnapCenter"]

* TR-4719: Replica del sistema SAP HANA: Backup e ripristino con SnapCenter
+
link:hana-sr-scs-system-replication-overview.html["Backup e ripristino con SnapCenter"]





== Cronologia delle versioni

|===
| Versione | Data | Cronologia delle versioni del documento 


| Versione 1.0 | Maggio 2022 | Release iniziale. 
|===