---
sidebar: sidebar 
permalink: backup/hana-hycl-backup-info-version.html 
keywords: BlueXP, SAP HANA, restore 
summary: Questa sezione elenca dove trovare ulteriori informazioni e mostra la cronologia delle versioni. 
---
= Informazioni aggiuntive e cronologia versioni
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Questa sezione elenca dove trovare ulteriori informazioni e mostra la cronologia delle versioni.



== Dove trovare ulteriori informazioni

Per ulteriori informazioni sulle informazioni descritte in questo documento, consultare i seguenti documenti e/o siti Web:

* Documentazione di backup e recovery di NetApp BlueXP +
https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-protect-app-data-to-cloud.html["Proteggi i dati delle applicazioni on-premise | documentazione NetApp"]
* Backup e recovery per SAP HANA con SnapCenter +
https://docs.netapp.com/us-en/netapp-solutions-sap/backup/saphana-br-scs-overview.html#the-netapp-solution[]




== Cronologia delle versioni

[cols="17%,23%,60%"]
|===
| Versione | Data | Cronologia delle versioni del documento 


| Versione 1.0 | Marzo 2024 | Versione iniziale 
|===
Fare riferimento a. http://mysupport.netapp.com/matrix["Tool di matrice di interoperabilità (IMT)"] Sul sito del supporto NetApp per verificare che le versioni esatte dei prodotti e delle funzionalità descritte in questo documento siano supportate per il tuo ambiente specifico. NetApp IMT definisce i componenti e le versioni dei prodotti che possono essere utilizzati per costruire configurazioni supportate da NetApp. I risultati specifici dipendono dall'installazione di ciascun cliente in conformità alle specifiche pubblicate.
