---
sidebar: sidebar 
permalink: backup/saphana-dr-anf_prepare_the_target_host.html 
keywords: prepare, target, host, target, host, server, hana, log, volume, configure, install 
summary: In questa sezione vengono descritte le fasi di preparazione necessarie per il server, che vengono utilizzate per il test di failover del disaster recovery. 
---
= Preparare l'host di destinazione
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:saphana-dr-anf_disaster_recovery_testing_overview.html["Precedente: Test di disaster recovery."]

In questa sezione vengono descritte le fasi di preparazione necessarie per il server utilizzato per il test di failover del disaster recovery.

Durante il normale funzionamento, l'host di destinazione viene generalmente utilizzato per altri scopi, ad esempio come sistema di test o QA HANA. Pertanto, la maggior parte di questi passaggi deve essere eseguita quando viene eseguito il test di failover di emergenza. D'altra parte, i file di configurazione pertinenti, come `/etc/fstab` e. `/usr/sap/sapservices`, può essere preparato e quindi messo in produzione semplicemente copiando il file di configurazione. La procedura di test del disaster recovery garantisce che i file di configurazione preparati siano configurati correttamente.

La preparazione dell'host di destinazione include anche lo spegnimento del sistema di test o QA HANA e l'interruzione di tutti i servizi `systemctl stop sapinit`.



== Nome host e indirizzo IP del server di destinazione

Il nome host del server di destinazione deve essere identico al nome host del sistema di origine. L'indirizzo IP può essere diverso.


NOTE: È necessario stabilire un corretto scherma del server di destinazione in modo che non possa comunicare con altri sistemi. Se non è disponibile un corretto scherma, il sistema di produzione clonato potrebbe scambiare dati con altri sistemi di produzione, causando la corruzione logica dei dati.



== Installare il software richiesto

Il software dell'agente host SAP deve essere installato sul server di destinazione. Per ulteriori informazioni, consultare https://help.sap.com/viewer/9f03f1852ce94582af41bb49e0a667a7/103/en-US["Agente host SAP"^] Nel portale di assistenza SAP.


NOTE: Se l'host viene utilizzato come sistema di test o QA HANA, il software dell'agente host SAP è già installato.



== Configurare utenti, porte e servizi SAP

Gli utenti e i gruppi richiesti per il database SAP HANA devono essere disponibili sul server di destinazione. In genere, viene utilizzata la gestione centrale degli utenti, pertanto non sono necessarie operazioni di configurazione sul server di destinazione. Le porte richieste per il database HANA devono essere configurate sugli host di destinazione. È possibile copiare la configurazione dal sistema di origine copiando `/etc/services` sul server di destinazione.

Le voci dei servizi SAP richieste devono essere disponibili sull'host di destinazione. È possibile copiare la configurazione dal sistema di origine copiando `/usr/sap/sapservices` sul server di destinazione. Il seguente output mostra le voci richieste per il database SAP HANA utilizzato nella configurazione di laboratorio.

....
vm-pr1:~ # cat /usr/sap/sapservices
#!/bin/sh
LD_LIBRARY_PATH=/usr/sap/PR1/HDB01/exe:$LD_LIBRARY_PATH;export LD_LIBRARY_PATH;/usr/sap/PR1/HDB01/exe/sapstartsrv pf=/usr/sap/PR1/SYS/profile/PR1_HDB01_vm-pr1 -D -u pr1adm
limit.descriptors=1048576
....


== Preparare il volume di log HANA

Poiché il volume di log HANA non fa parte della replica, è necessario che nell'host di destinazione esista un volume di log vuoto. Il volume di log deve includere le stesse sottodirectory del sistema HANA di origine.

....
vm-pr1:~ # ls -al /hana/log/PR1/mnt00001/
total 16
drwxrwxrwx 5 root   root   4096 Feb 19 16:20 .
drwxr-xr-x 3 root   root     22 Feb 18 13:38 ..
drwxr-xr-- 2 pr1adm sapsys 4096 Feb 22 10:25 hdb00001
drwxr-xr-- 2 pr1adm sapsys 4096 Feb 22 10:25 hdb00002.00003
drwxr-xr-- 2 pr1adm sapsys 4096 Feb 22 10:25 hdb00003.00003
vm-pr1:~ #
....


== Preparare il volume di backup del log

Poiché il sistema di origine è configurato con un volume separato per i backup del registro HANA, un volume di backup del registro deve essere disponibile anche sull'host di destinazione. Un volume per i backup del log deve essere configurato e montato sull'host di destinazione.

Se la replica del volume di backup del registro fa parte della configurazione del disaster recovery, un nuovo volume basato su uno snapshot viene montato sull'host di destinazione e non è necessario preparare un volume di backup del registro aggiuntivo.



== Preparare i montaggi del file system

La seguente tabella mostra le convenzioni di denominazione utilizzate nella configurazione di laboratorio. I nomi dei volumi dei nuovi volumi nel sito di disaster recovery sono inclusi in `/etc/fstab`. Questi nomi di volume vengono utilizzati nella fase di creazione del volume nella sezione successiva.

|===
| Volumi HANA PR1 | Nuovi volumi e sottodirectory nel sito di disaster recovery | Punto di montaggio sull'host di destinazione 


| Volume di dati | PR1-data-mnt00001-SM-dest-clone | /hana/data/PR1/mnt00001 


| Volume condiviso | PR1-shared-sm-dest-clone/shared PR1-shared-sm-dest-clone/usr-sap-PR1 | /hana/shared /usr/sap/PR1 


| Volume di backup del registro | hanabackup-sm-dest-clone | /hanabackup 
|===

NOTE: I punti di montaggio elencati in questa tabella devono essere creati sull'host di destinazione.

Ecco i requisiti `/etc/fstab` voci.

....
vm-pr1:~ # cat /etc/fstab
# HANA ANF DB Mounts
10.0.2.4:/PR1-data-mnt00001-sm-dest-clone /hana/data/PR1/mnt00001 nfs   rw,vers=4,minorversion=1,hard,timeo=600,rsize=262144,wsize=262144,intr,noatime,lock,_netdev,sec=sys  0  0
10.0.2.4:/PR1-log-mnt00001-dr /hana/log/PR1/mnt00001 nfs   rw,vers=4,minorversion=1,hard,timeo=600,rsize=262144,wsize=262144,intr,noatime,lock,_netdev,sec=sys  0  0
# HANA ANF Shared Mounts
10.0.2.4:/PR1-shared-sm-dest-clone/hana-shared /hana/shared nfs rw,vers=4,minorversion=1,hard,timeo=600,rsize=262144,wsize=262144,intr,noatime,lock,_netdev,sec=sys  0  0
10.0.2.4:/PR1-shared-sm-dest-clone/usr-sap-PR1 /usr/sap/PR1 nfs rw,vers=4,minorversion=1,hard,timeo=600,rsize=262144,wsize=262144,intr,noatime,lock,_netdev,sec=sys  0  0
# HANA file and log backup destination
10.0.2.4:/hanabackup-sm-dest-clone    /hanabackup nfs   rw,vers=3,hard,timeo=600,rsize=262144,wsize=262144,nconnect=8,bg,noatime,nolock 0 0
....
link:saphana-dr-anf_create_new_volumes_based_on_snapshot_backups_at_the_disaster_recovery_site.html["Pagina successiva: Creazione di nuovi volumi in base ai backup snapshot nel sito di disaster recovery."]
