---
sidebar: sidebar 
permalink: backup/saphana-backup-anf-overview.html 
keywords: overview, introduction, tr-4905, 4905, tr4905, snapcenter service, anf, azure netapp files 
summary: Questo report tecnico illustra le Best practice per la protezione dei dati SAP HANA con NetApp SnapCenter Service e Azure NetApp Files. Descrive i concetti del servizio SnapCenter, i consigli di configurazione e i flussi di lavoro delle operazioni, incluse le operazioni di backup e ripristino e recovery. 
---
= TR-4905: Backup e ripristino SAP HANA su Azure NetApp Files con servizio SnapCenter
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Questo report tecnico illustra le Best practice per la protezione dei dati SAP HANA con NetApp SnapCenter Service e Azure NetApp Files. Descrive i concetti del servizio SnapCenter, i consigli di configurazione e i flussi di lavoro delle operazioni, incluse le operazioni di backup e ripristino e recovery.

Autore: Nils Bauer, NetApp

Le aziende oggi richiedono una disponibilità continua e ininterrotta per le proprie applicazioni SAP. Si aspettano livelli di performance costanti di fronte a volumi di dati in continua crescita e alla necessità di attività di manutenzione ordinaria come i backup di sistema. L'esecuzione di backup dei database SAP è un'attività critica e può avere un impatto significativo sulle performance del sistema SAP di produzione.

Le finestre di backup si stanno riducendo, mentre la quantità di dati da sottoporre a backup aumenta. Pertanto, è difficile trovare un momento in cui i backup possono essere eseguiti con un effetto minimo sui processi di business. Il tempo necessario per ripristinare e ripristinare i sistemi SAP è un problema, perché i downtime per i sistemi di produzione SAP e non in produzione devono essere ridotti al minimo per ridurre la perdita di dati e i costi per l'azienda.

I seguenti punti riassumono le sfide che devono affrontare il backup e il recovery SAP:

* *Effetti delle performance sui sistemi SAP di produzione.* in genere, i backup tradizionali basati su copia creano un significativo scolo delle performance sui sistemi SAP di produzione a causa dei carichi pesanti posti sul server di database, sul sistema storage e sulla rete storage.
* *Riduzione delle finestre di backup.* i backup convenzionali possono essere eseguiti solo quando sono in corso poche attività di dialogo o batch sul sistema SAP. La pianificazione dei backup diventa più difficile quando i sistemi SAP vengono utilizzati 24 ore su 24.
* *Rapida crescita dei dati.* la rapida crescita dei dati e la riduzione delle finestre di backup richiedono investimenti continui nell'infrastruttura di backup. In altre parole, è necessario ottenere ulteriore spazio su disco per il backup e reti di backup più veloci. È inoltre necessario coprire le spese in corso relative all'archiviazione e alla gestione di queste risorse di backup. I backup incrementali o differenziali possono risolvere questi problemi, ma questa disposizione comporta un processo di ripristino molto lento, complicato e complesso, più difficile da verificare. Tali sistemi di solito aumentano i tempi di obiettivi del tempo di ripristino (RTO) e di obiettivi del punto di ripristino (RPO) in modi che non sono accettabili per l'azienda.
* *Aumento del costo del downtime.* il downtime non pianificato di un sistema SAP influisce in genere sulle finanze aziendali. Una parte significativa di qualsiasi downtime non pianificato viene consumata dal requisito di ripristino e ripristino del sistema SAP. Pertanto, l'RTO desiderato determina la progettazione dell'architettura di backup e ripristino.
* *Tempi di backup e recovery per i progetti di upgrade SAP.* il piano di progetto per un upgrade SAP include almeno tre backup del database SAP. Questi backup riducono significativamente il tempo disponibile per il processo di aggiornamento. La decisione di procedere si basa generalmente sul tempo necessario per ripristinare e ripristinare il database dal backup creato in precedenza. Invece di ripristinare semplicemente un sistema allo stato precedente, un ripristino rapido offre più tempo per risolvere i problemi che potrebbero verificarsi durante un aggiornamento.

