---
sidebar: sidebar 
permalink: backup/saphana-br-scs-where-to-find-additional-information.html 
keywords:  
summary:  
---
= Dove trovare informazioni aggiuntive e cronologia delle versioni
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Per ulteriori informazioni sulle informazioni descritte in questo documento, consultare i seguenti documenti e/o siti Web:

* Pagina delle risorse SnapCenter
+
https://www.netapp.com/us/documentation/snapcenter-software.aspx["https://www.netapp.com/us/documentation/snapcenter-software.aspx"]

* Documentazione software SnapCenter
+
https://docs.netapp.com/us-en/snapcenter/index.html["https://docs.netapp.com/us-en/snapcenter/index.html"^]

* TR-4667: Automazione delle copie del sistema SAP con SnapCenter
+
https://www.netapp.com/pdf.html?item=/media/17111-tr4667pdf.pdf["https://www.netapp.com/pdf.html?item=/media/17111-tr4667pdf.pdf"^]

* TR-4719: Replica, backup e ripristino del sistema SAP HANA con SnapCenter
+
https://www.netapp.com/pdf.html?item=/media/17030-tr4719pdf.pdf["https://www.netapp.com/pdf.html?item=/media/17030-tr4719pdf.pdf"^]

* TR-4018: Integrazione dei sistemi NetApp ONTAP con la gestione del panorama SAP
+
https://www.netapp.com/pdf.html?item=/media/17195-tr4018pdf.pdf["https://www.netapp.com/pdf.html?item=/media/17195-tr4018pdf.pdf"^]

* TR-4646: Disaster recovery SAP HANA con replica dello storage
+
https://www.netapp.com/pdf.html?item=/media/8584-tr4646pdf.pdf["https://www.netapp.com/pdf.html?item=/media/8584-tr4646pdf.pdf"^]





== Cronologia delle versioni

|===
| Versione | Data | Cronologia delle versioni del documento 


| Versione 1.0 | Luglio 2017  a| 
* Release iniziale.




| Versione 1.1 | Settembre 2017  a| 
* Aggiunta della sezione "Configurazione e ottimizzazione avanzate".
* Correzioni minori.




| Versione 2.0 | Marzo 2018  a| 
* Aggiornamenti per SnapCenter 4,0:
Nuova risorsa del volume di dati
Miglioramento del funzionamento di Single file SnapRestore




| Versione 3.0 | Gennaio 2020  a| 
* Aggiunta la sezione "concetti e Best practice SnapCenter".
* Aggiornamenti per SnapCenter 4,3:
Rilevamento automatico
Ripristino e ripristino automatici
Supporto di tenant multipli HANA MDC
Operazione di ripristino single-tenant




| Versione 3.1 | Luglio 2020  a| 
* Aggiornamenti e correzioni minori:
Supporto NFSv4 con SnapCenter 4.3.1
Configurazione della comunicazione SSL
Implementazione centralizzata dei plug-in per Linux su IBM Power




| Versione 3.2 | Novembre 2020  a| 
* Aggiunti i privilegi utente del database richiesti per HANA 2.0 SPS5.




| Versione 3.3 | Maggio 2021  a| 
* Aggiornata la sezione di configurazione di SSL hdbsql.
* Supporto LVM Linux aggiunto.




| Versione 3.4 | Agosto 2021  a| 
* È stata aggiunta la descrizione della configurazione per la disattivazione del rilevamento automatico.




| Versione 3.5 | Febbraio 2022  a| 
* Aggiornamenti minori per SnapCenter 4.6 e supporto del rilevamento automatico per i sistemi HANA abilitati alla replica del sistema HANA.


|===