---
sidebar: sidebar 
permalink: backup/saphana-san_pdf_link.html 
keywords: nva-1147, pdf, sap, hana, disaster, recovery, data protection, dr, snapmirror, snapcenter, commvault 
summary: 'Questa architettura verificata di NetApp copre la modernizzazione dei sistemi e delle operazioni SAP per SAP HANA su sistemi storage All SAN Array (ASA) NetApp con Brocade FC SAN Fabric. Include backup e ripristino, disaster recovery e protezione dei dati.' 
---
= NVA-1147-DESIGN: SAP HANA su NetApp All SAN Array - SAN moderne, protezione dei dati e disaster recovery
:allow-uri-read: 


[role="lead"]
Questa architettura verificata di NetApp copre la modernizzazione dei sistemi e delle operazioni SAP per SAP HANA su sistemi storage All SAN Array (ASA) NetApp con Brocade FC SAN Fabric. Include backup e ripristino, disaster recovery e protezione dei dati. La soluzione sfrutta NetApp SnapCenter per automatizzare backup, ripristino e recovery SAP HANA, oltre a clonare i flussi di lavoro. Gli scenari di configurazione, test e failover del disaster recovery vengono descritti utilizzando il software di replica dei dati sincrono NetApp SnapMirror. Inoltre, viene illustrata la protezione dei dati SAP con CommVault.

Autori:

Nils Bauer, Roland Wartenberg, Darryl Clinkscales, Daniel Hohman, Marco Schöen, Steve Botkin, Michael Peppers, Vidula Aiker, Steve Collins, Pavan Jhamnani, Lee Dorrier, NetApp Jim Zucchero, Naem Saafein, pH.D., Broadcom Brocade

link:https://www.netapp.com/pdf.html?item=/media/10235-nva-1147-design.pdf["https://www.netapp.com/pdf.html?item=/media/10235-nva-1147-design.pdf"]
