---
sidebar: sidebar 
permalink: bp/hana-fas-nfs-additional-info.html 
keywords: additional, information, fas, nfs, sap, hana 
summary: Per ulteriori informazioni sulle informazioni descritte in questo documento, consultare i seguenti documenti e/o siti Web. 
---
= Dove trovare ulteriori informazioni
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Per ulteriori informazioni sulle informazioni descritte in questo documento, consultare i seguenti documenti e/o siti Web:

* link:../index.html["Soluzioni software SAP HANA"^]
* link:../backup/hana-dr-sr-pdf-link.html["Disaster recovery SAP HANA con replica dello storage"^]
* link:../backup/hana-sc-generic-scope.html["Backup e ripristino SAP HANA con SnapCenter"^]
* link:../lifecycle/sc-copy-clone-introduction.html["Automazione delle copie del sistema SAP tramite il plug-in SnapCenter SAP HANA"^]
* Centri di documentazione NetApp
+
https://www.netapp.com/support-and-training/documentation/["https://www.netapp.com/support-and-training/documentation/"^]

* Hardware per lo storage aziendale certificato SAP per SAP HANA
+
https://www.sap.com/dmc/exp/2014-09-02-hana-hardware/enEN/["https://www.sap.com/dmc/exp/2014-09-02-hana-hardware/enEN/"^]

* Requisiti di storage SAP HANA
+
https://help.sap.com/docs/SAP_HANA_PLATFORM/eb3777d5495d46c5b2fa773206bbfb46/0b15a92d554c4941a452c9ca127f8c70.html^[]]

* Integrazione SAP HANA Tailored Data Center
+
https://www.sap.com/documents/2016/05/e8705aae-717c-0010-82c7-eda71af511fa.html["https://www.sap.com/documents/2016/05/e8705aae-717c-0010-82c7-eda71af511fa.html"^]

* SAP HANA su VMware vSphere Wiki
+
https://help.sap.com/docs/SUPPORT_CONTENT/virtualization/3362185751.html["https://help.sap.com/docs/SUPPORT_CONTENT/virtualization/3362185751.html"^]

* Guida alle Best practice di SAP HANA su VMware vSphere
+
https://www.vmware.com/docs/sap_hana_on_vmware_vsphere_best_practices_guide-white-paper["https://www.vmware.com/docs/sap_hana_on_vmware_vsphere_best_practices_guide-white-paper"^]


