---
sidebar: sidebar 
permalink: bp/hana-aff-nfs-additional-info.html 
keywords:  
summary:  
---
= Dove trovare ulteriori informazioni
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Per ulteriori informazioni sulle informazioni descritte in questo documento, consultare i seguenti documenti e/o siti Web:

* link:../index.html["Soluzioni software SAP HANA"]
* link:../backup/hana-dr-sr-pdf-link.html["TR-4646: Disaster recovery SAP HANA con replica dello storage"]
* link:../backup/hana-br-scs-overview.html["TR-4614: Backup e ripristino SAP HANA con SnapCenter"]
* link:../lifecycle/sc-copy-clone-introduction.html["TR-4667: Automatizzazione di copie di sistema SAP con il plug-in SAP HANA SnapCenter"]
* Centri di documentazione NetApp
+
https://www.netapp.com/support-and-training/documentation/["https://www.netapp.com/support-and-training/documentation/"^]

* Hardware per lo storage aziendale certificato SAP per SAP HANA
+
https://www.sap.com/dmc/exp/2014-09-02-hana-hardware/enEN/["https://www.sap.com/dmc/exp/2014-09-02-hana-hardware/enEN/"^]

* Requisiti di storage SAP HANA
+
https://www.sap.com/documents/2024/03/146274d3-ae7e-0010-bca6-c68f7e60039b.html["https://www.sap.com/documents/2024/03/146274d3-ae7e-0010-bca6-c68f7e60039b.html"^]

* SAP HANA - Domande frequenti sull'integrazione personalizzata del data center
+
https://www.sap.com/documents/2016/05/e8705aae-717c-0010-82c7-eda71af511fa.html["https://www.sap.com/documents/2016/05/e8705aae-717c-0010-82c7-eda71af511fa.html"^]

* SAP HANA su VMware vSphere Wiki
+
https://help.sap.com/docs/SUPPORT_CONTENT/virtualization/3362185751.html["https://help.sap.com/docs/SUPPORT_CONTENT/virtualization/3362185751.html"^]

* Guida alle Best practice di SAP HANA su VMware vSphere
+
https://www.vmware.com/docs/sap_hana_on_vmware_vsphere_best_practices_guide-white-paper["https://www.vmware.com/docs/sap_hana_on_vmware_vsphere_best_practices_guide-white-paper"^]


