---
sidebar: sidebar 
permalink: bp/hana-asa-fc-io-stack-configuration.html 
keywords: io, i/o, stack, configuration, database 
summary: A partire da SAP HANA 1.0 SPS10, SAP ha introdotto i parametri per regolare il comportamento di i/o e ottimizzare il database per il file e il sistema storage utilizzati. 
---
= Configurazione dello stack di i/o per SAP HANA
:allow-uri-read: 




== Configurazione dello stack di i/o per SAP HANA

A partire da SAP HANA 1.0 SPS10, SAP ha introdotto i parametri per regolare il comportamento di i/o e ottimizzare il database per il file e il sistema storage utilizzati.

NetApp ha condotto test delle performance per definire i valori ideali. La seguente tabella elenca i valori ottimali dedotti dai test delle prestazioni.

|===
| Parametro | Valore 


| max_parallel_io_requests | 128 


| async_read_submit | acceso 


| async_write_submit_active | acceso 


| async_write_submit_blocks | tutto 
|===
Per i sistemi da SAP HANA 1.0 a SPS12, questi parametri possono essere impostati durante l'installazione del database SAP HANA, come descritto nella nota SAP https://launchpad.support.sap.com/["2267798 – Configurazione del database SAP HANA durante l'installazione con hdbparam"^].

In alternativa, è possibile impostare i parametri dopo l'installazione del database SAP HANA utilizzando `hdbparam` framework.

....
FC5adm@sapcc-hana-tst:/usr/sap/FC5/HDB00> hdbparam --paramset fileio.max_parallel_io_requests=128
FC5adm@sapcc-hana-tst:/usr/sap/FC5/HDB00> hdbparam --paramset fileio.async_write_submit_active=on
FC5adm@sapcc-hana-tst:/usr/sap/FC5/HDB00> hdbparam --paramset fileio.async_read_submit=on
FC5adm@sapcc-hana-tst:/usr/sap/FC5/HDB00> hdbparam --paramset fileio.async_write_submit_blocks=all
....
A partire da SAP HANA 2.0, `hdbparam` è obsoleto e i parametri vengono spostati su `global.ini` file. I parametri possono essere impostati utilizzando i comandi SQL o SAP HANA Studio. Per ulteriori informazioni, fare riferimento alla nota SAP https://launchpad.support.sap.com/["2399079: Eliminazione di hdbparam in HANA 2"^]. I parametri possono essere impostati anche all'interno di `global.ini` file.

....
FC5adm@sapcc-hana-tst: /usr/sap/FC5/SYS/global/hdb/custom/config> cat global.ini
…
[fileio]
async_read_submit = on
async_write_submit_active = on
max_parallel_io_requests = 128
async_write_submit_blocks = all
…
....
Per SAP HANA 2.0 SPS5 e versioni successive, utilizzare `setParameter.py` script per impostare i parametri corretti.

....
fc5adm@sapcc-hana-tst-03:/usr/sap/FC5/HDB00/exe/python_support>
python setParameter.py -set=SYSTEM/global.ini/fileio/max_parallel_io_requests=128
python setParameter.py -set=SYSTEM/global.ini/fileio/async_read_submit=on
python setParameter.py -set=SYSTEM/global.ini/fileio/async_write_submit_active=on
python setParameter.py -set=SYSTEM/global.ini/fileio/async_write_submit_blocks=all
....