---
sidebar: sidebar 
permalink: bp/hana-asa-fc-storage-controller-setup_multiple_hosts.html 
keywords: storage efficiency, netapp volume encryption, quality of service, qos, fabricpool, Disk shelf, sas, fcp port sets, linux lvm, 
summary: Questa sezione descrive come creare LUN per un sistema host multiplo 
---
= Configurazione del controller di archiviazione: più host
:allow-uri-read: 




== Configurazione del controller di archiviazione: più host

[role="lead"]
Questa sezione descrive la configurazione del sistema di archiviazione NetApp specifico per i sistemi multi-host SAP HANA



== Configurazione LUN per sistemi multi-host SAP HANA

Linux LVM viene utilizzato per aumentare le prestazioni e risolvere i limiti delle dimensioni LUN.

Nell'host SAP HANA, è necessario creare e montare gruppi di volumi e volumi logici, come indicato nella tabella seguente.

|===
| Volume logico (LV) | Punto di montaggio sull'host SAP HANA | Nota 


| LV: FC5_data_mnt00001-vol | /hana/data/FC5/mnt00001 | Montato utilizzando un connettore storage 


| LV: FC5_log_mnt00001-vol | /hana/log/FC5/mnt00001 | Montato utilizzando un connettore storage 


| LV: FC5_data_mnt00002-vol | /hana/data/FC5/mnt00002 | Montato utilizzando un connettore storage 


| LV: FC5_log_mnt00002-vol | /hana/log/FC5/mnt00002 | Montato utilizzando un connettore storage 


| Condivisione NFS esterna: FC5_shared | /hana/shared | Montato su tutti gli host usando NFS e /etc/fstab entry 
|===

NOTE: I sistemi multi-host SAP HANA richiedono  `/hana/shared` File system connesso a tutti gli host di un sistema. Solitamente si tratta di una condivisione NFS fornita da un server NFS. Si consiglia di utilizzare un server NFS ad alta disponibilità, ad esempio un sistema NetApp FAS o AFF. Un'altra opzione è quella di utilizzare il server NFS integrato di un host LINUX.


NOTE: Con la configurazione descritta, il  `/usr/sap/FC5` La directory in cui è memorizzata la directory home predefinita dell'utente FC5adm si trova sul disco locale di ciascun host HANA. In una configurazione di disaster recovery con replica basata su disco, NetApp consiglia di utilizzare quattro LUN aggiuntive per  `/usr/sap/FC5` file system di ciascun host in modo che ogni host del database abbia tutti i suoi file system sullo storage centrale.



== Creazione di LUN e mappatura delle LUN ai gruppi di iniziatori

Puoi utilizzare NetApp ONTAP System Manager per creare volumi di storage e LUN e associarli agli igroup dei server e all'interfaccia a riga di comando di ONTAP. In questa guida viene descritto l'utilizzo della CLI.


NOTE: Il `sanlun` Fa parte delle utility host di NetApp e deve essere installato su ciascun host SAP HANA. Per ulteriori informazioni, vedere la sezione "host_setup".



=== Creazione di LUN e mappatura delle LUN ai gruppi di iniziatori tramite la CLI

Questa sezione mostra un esempio di configurazione utilizzando la riga di comando con ONTAP 9 per un sistema host multiplo SAP HANA 2+1 con FC5 FC5 utilizzando LVM e due LUN per gruppo di volumi LVM:

. Creare tutte le LUN.
+
....
lun create -path FC5_data_mnt00001   -size 1t -ostype linux  -class regular
lun create -path FC5_data2_mnt00001 -size 1t -ostype linux  -class regular
lun create -path FC5_data_mnt00002 -size 1t -ostype linux  -class regular
lun create -path FC5_data2_mnt00002 -size 1t -ostype linux  -class regular
lun create -path FC5_log_mnt00001 -size 260g -ostype linux  -class regular
lun create -path FC5_log2_mnt00001 -size 260g -ostype linux  -class regular
lun create -path FC5_log_mnt00002 -size 260g -ostype linux  -class regular
lun create -path FC5_log2_mnt00002 -size 260g -ostype linux  -class regular
....
. Creare il gruppo iniziatore per tutti i server appartenenti al sistema FC5.
+
....
lun igroup create -igroup HANA-FC5 -protocol fcp -ostype linux -initiator 10000090fadcc5fa,10000090fadcc5fb,10000090fadcc5c1,10000090fadcc5c2,10000090fadcc5c3,10000090fadcc5c4 -vserver svm1
....
. Mappare tutti i LUN al gruppo iniziatore creato.
+
....
lun map -path FC5_data_mnt00001  -igroup HANA-FC5
lun map -path FC5_data2_mnt00001  -igroup HANA-FC5
lun map -path FC5_data_mnt00002  -igroup HANA-FC5
lun map -path FC5_data2_mnt00002  -igroup HANA-FC5
lun map -path FC5_log_mnt00001  -igroup HANA-FC5
lun map -path FC5_log2_mnt00001  -igroup HANA-FC5
lun map -path FC5_log_mnt00002  -igroup HANA-FC5
lun map -path FC5_log2_mnt00002  -igroup HANA-FC5
....

