---
sidebar: sidebar 
permalink: bp/hana-aff-fc-software-install.html 
keywords: software, installation, 
summary: Questa sezione descrive la preparazione necessaria per installare SAP HANA su sistemi a host singolo e su sistemi a più host. 
---
= Installazione del software SAP HANA
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Questa sezione descrive la preparazione necessaria per installare SAP HANA su sistemi a host singolo e su sistemi a più host.



== Installazione su sistema a host singolo

L'installazione del software SAP HANA non richiede alcuna preparazione aggiuntiva per un sistema a singolo host.



== Installazione su sistemi a più host

Prima di iniziare l'installazione, creare un `global.ini` File per abilitare l'utilizzo di SAP Storage Connector durante il processo di installazione. Il connettore di storage SAP monta i file system richiesti sugli host di lavoro durante il processo di installazione. Il `global.ini` il file deve essere disponibile in un file system accessibile da tutti gli host, ad esempio `/hana/shared` file system.

Prima di installare il software SAP HANA su un sistema a più host, è necessario completare la seguente procedura:

. Aggiungere le seguenti opzioni di montaggio per i LUN dei dati e i LUN del registro a `global.ini` file:
+
** `relatime` e. `inode64` per il file system di dati e log


. Aggiungere i WWID delle partizioni dei dati e dei log. Gli ID WWID devono corrispondere ai nomi alias configurati in `/etc/multipath.conf` file.
+
L'output seguente mostra un esempio di una configurazione multi-host 2+1 utilizzando LVM con SID=FC5.

+
....
sapcc-hana-tst-03:/hana/shared # cat global.ini
[communication]
listeninterface = .global
[persistence]
basepath_datavolumes = /hana/data/FC5
basepath_logvolumes = /hana/log/FC5
[storage]
ha_provider = hdb_ha.fcClientLVM
partition_*_*__prtype = 5
partition_*_data__mountOptions = -o relatime,inode64
partition_*_log__mountOptions = -o relatime,inode64
partition_1_data__lvmname = FC5_data_mnt00001-vol
partition_1_log__lvmname = FC5_log_mnt00001-vol
partition_2_data__lvmname = FC5_data_mnt00002-vol
partition_2_log__lvmname = FC5_log_mnt00002-vol
sapcc-hana-tst-03:/hana/shared #
....
+
Utilizzando lo strumento di installazione SAP hdblcm, avviare l'installazione eseguendo il seguente comando su uno degli host worker. Utilizzare l' `addhosts`opzione per aggiungere il secondo lavoratore (sapcc-hana-tst-06) e l'host di standby (sapcc-hana-tst-07).

+

NOTE: La directory in cui è memorizzato il file preparato `global.ini` è inclusa con l' `storage_cfg`opzione CLI (`--storage_cfg=/hana/shared`).

+

NOTE: A seconda della versione del sistema operativo in uso, potrebbe essere necessario installare Python 2.7 prima di installare il database SAP HANA.

+
....
./hdblcm --action=install --addhosts=sapcc-hana-tst-06:role=worker:storage_partition=2,sapcc-hana-tst-07:role=standby --storage_cfg=/hana/shared/

AP HANA Lifecycle Management - SAP HANA Database 2.00.073.00.1695288802
************************************************************************


Scanning software locations...
Detected components:
    SAP HANA AFL (incl.PAL,BFL,OFL) (2.00.073.0000.1695321500) in /mnt/sapcc-share/software/SAP/HANA2SPS7-73/DATA_UNITS/HDB_AFL_LINUX_X86_64/packages
    SAP HANA Database (2.00.073.00.1695288802) in /mnt/sapcc-share/software/SAP/HANA2SPS7-73/DATA_UNITS/HDB_SERVER_LINUX_X86_64/server
    SAP HANA Database Client (2.18.24.1695756995) in /mnt/sapcc-share/software/SAP/HANA2SPS7-73/DATA_UNITS/HDB_CLIENT_LINUX_X86_64/SAP_HANA_CLIENT/client
    SAP HANA Studio (2.3.75.000000) in /mnt/sapcc-share/software/SAP/HANA2SPS7-73/DATA_UNITS/HDB_STUDIO_LINUX_X86_64/studio
    SAP HANA Local Secure Store (2.11.0) in /mnt/sapcc-share/software/SAP/HANA2SPS7-73/DATA_UNITS/HANA_LSS_24_LINUX_X86_64/packages
    SAP HANA XS Advanced Runtime (1.1.3.230717145654) in /mnt/sapcc-share/software/SAP/HANA2SPS7-73/DATA_UNITS/XSA_RT_10_LINUX_X86_64/packages
    SAP HANA EML AFL (2.00.073.0000.1695321500) in /mnt/sapcc-share/software/SAP/HANA2SPS7-73/DATA_UNITS/HDB_EML_AFL_10_LINUX_X86_64/packages
    SAP HANA EPM-MDS (2.00.073.0000.1695321500) in /mnt/sapcc-share/software/SAP/HANA2SPS7-73/DATA_UNITS/SAP_HANA_EPM-MDS_10/packages
    Automated Predictive Library (4.203.2321.0.0) in /mnt/sapcc-share/software/SAP/HANA2SPS7-73/DATA_UNITS/PAAPL4_H20_LINUX_X86_64/apl-4.203.2321.0-hana2sp03-linux_x64/installer/packages
    GUI for HALM for XSA (including product installer) Version 1 (1.015.0) in /mnt/sapcc-share/software/SAP/HANA2SPS7-73/DATA_UNITS/XSA_CONTENT_10/XSACALMPIUI15_0.zip
    XSAC FILEPROCESSOR 1.0 (1.000.102) in /mnt/sapcc-share/software/SAP/HANA2SPS7-73/DATA_UNITS/XSA_CONTENT_10/XSACFILEPROC00_102.zip
    SAP HANA tools for accessing catalog content, data preview, SQL console, etc. (2.015.230503) in /mnt/sapcc-share/software/SAP/HANA2SPS7-73/DATA_UNITS/XSAC_HRTT_20/XSACHRTT15_230503.zip
    Develop and run portal services for customer applications on XSA (2.007.0) in /mnt/sapcc-share/software/SAP/HANA2SPS7-73/DATA_UNITS/XSA_CONTENT_10/XSACPORTALSERV07_0.zip
    The SAP Web IDE for HANA 2.0 (4.007.0) in /mnt/sapcc-share/software/SAP/HANA2SPS7-73/DATA_UNITS/XSAC_SAP_WEB_IDE_20/XSACSAPWEBIDE07_0.zip
    XS JOB SCHEDULER 1.0 (1.007.22) in /mnt/sapcc-share/software/SAP/HANA2SPS7-73/DATA_UNITS/XSA_CONTENT_10/XSACSERVICES07_22.zip
    SAPUI5 FESV6 XSA 1 - SAPUI5 1.71 (1.071.52) in /mnt/sapcc-share/software/SAP/HANA2SPS7-73/DATA_UNITS/XSA_CONTENT_10/XSACUI5FESV671_52.zip
    SAPUI5 FESV9 XSA 1 - SAPUI5 1.108 (1.108.5) in /mnt/sapcc-share/software/SAP/HANA2SPS7-73/DATA_UNITS/XSA_CONTENT_10/XSACUI5FESV9108_5.zip
    SAPUI5 SERVICE BROKER XSA 1 - SAPUI5 Service Broker 1.0 (1.000.4) in /mnt/sapcc-share/software/SAP/HANA2SPS7-73/DATA_UNITS/XSA_CONTENT_10/XSACUI5SB00_4.zip
    XSA Cockpit 1 (1.001.37) in /mnt/sapcc-share/software/SAP/HANA2SPS7-73/DATA_UNITS/XSA_CONTENT_10/XSACXSACOCKPIT01_37.zip


SAP HANA Database version '2.00.073.00.1695288802' will be installed.

Select additional components for installation:

  Index | Components      | Description
  --------------------------------------------------------------------------------------------------
  1     | all             | All components
  2     | server          | No additional components
  3     | client          | Install SAP HANA Database Client version 2.18.24.1695756995
  4     | lss             | Install SAP HANA Local Secure Store version 2.11.0
  5     | studio          | Install SAP HANA Studio version 2.3.75.000000
  6     | xs              | Install SAP HANA XS Advanced Runtime version 1.1.3.230717145654
  7     | afl             | Install SAP HANA AFL (incl.PAL,BFL,OFL) version 2.00.073.0000.1695321500
  8     | eml             | Install SAP HANA EML AFL version 2.00.073.0000.1695321500
  9     | epmmds          | Install SAP HANA EPM-MDS version 2.00.073.0000.1695321500
  10    | sap_afl_sdk_apl | Install Automated Predictive Library version 4.203.2321.0.0

Enter comma-separated list of the selected indices [3,4]: 2,3

....
. Verificare che lo strumento di installazione abbia installato tutti i componenti selezionati su tutti gli host di lavoro e di standby.

