---
sidebar: sidebar 
permalink: bp/hana-fas-nfs-install-prep-nfsv4.html 
keywords: sap, hana, installation, preparations, nfsv4, user, authentication, storage, controller, hosts 
summary: 'NFS versione 4 e successive richiede l"autenticazione dell"utente. Questa autenticazione può essere eseguita utilizzando uno strumento di gestione utente centrale, ad esempio un server LDAP (Lightweight Directory Access Protocol) o con account utente locali.' 
---
= Preparazione dell'installazione di SAP HANA per NFSv4
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NFS versione 4 e successive richiede l'autenticazione dell'utente. Questa autenticazione può essere eseguita utilizzando uno strumento di gestione utente centrale, ad esempio un server LDAP (Lightweight Directory Access Protocol) o con account utente locali. Le sezioni seguenti descrivono come configurare gli account utente locali.

Gli utenti amministrativi `<sid>adm`,`<sid>crypt` e il `sapsys` gruppo devono essere creati manualmente sugli host SAP HANA e sugli storage controller prima che venga avviata l'installazione del software SAP HANA.



== Host SAP HANA

Se non esiste, il `sapsys` Il gruppo deve essere creato sull'host SAP HANA. È necessario scegliere un ID di gruppo univoco che non sia in conflitto con gli ID di gruppo esistenti sui controller di storage.

Gli utenti `<sid>adm` e `<sid>crypt` vengono creati sull'host SAP HANA. È necessario scegliere ID univoci che non siano in conflitto con gli ID utente esistenti sui controller di archiviazione.

Per un sistema SAP HANA con host multipli, gli ID utente e gruppo devono essere gli stessi su tutti gli host SAP HANA. Il gruppo e l'utente vengono creati sugli altri host SAP HANA copiando le linee interessate da e `/etc/passwd` nel `/etc/group` sistema di origine a tutti gli altri host SAP HANA.


NOTE: Il dominio NFSv4 deve essere impostato sullo stesso valore su tutti i server Linux  `/etc/idmapd.conf`) E SVM. Impostare il parametro di dominio "dominio = <domain-name>" nel file `/etc/idmapd.conf` Per gli host Linux.

Attivare e avviare il servizio NFS IDMAPD.

....
systemctl enable nfs-idmapd.service
systemctl start nfs-idmapd.service
....

NOTE: I kernel Linux più recenti non richiedono questo passaggio. I messaggi di avviso possono essere ignorati in modo sicuro.



== Controller di storage

Gli ID utente e l'ID del gruppo devono essere gli stessi sugli host SAP HANA e sugli storage controller. Il gruppo e l'utente vengono creati immettendo i seguenti comandi sul cluster di storage:

....
vserver services unix-group create -vserver <vserver> -name <group name> -id <group id>
vserver services unix-user create -vserver <vserver> -user <user name> -id <user-id> -primary-gid <group id>
....
Inoltre, impostare l'ID del gruppo della root utente UNIX della SVM su 0.

....
vserver services unix-user modify -vserver <vserver> -user root -primary-gid 0
....