---
sidebar: sidebar 
permalink: bp/kvm-hana-requirements.html 
keywords: requirements,KVM, SAP HANA, tailored data center integration, FCP, NFS, prerequisites 
summary: Esaminare i requisiti per la distribuzione di SAP HANA Single-Host su SUSE KVM utilizzando storage NetApp con interfacce di rete SR-IOV e protocolli di storage NFS o FCP. 
---
= Requisiti di distribuzione per SAP HANA su SUSE KVM con storage NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Esaminare i requisiti per la distribuzione di SAP HANA Single-Host su SUSE KVM utilizzando storage NetApp con interfacce di rete SR-IOV e protocolli di storage NFS o FCP.

Per l'implementazione sono necessari server SAP HANA certificati, sistemi di storage NetApp , schede di rete compatibili con SR-IOV e SUSE Linux Enterprise Server per applicazioni SAP come host KVM.



== Requisiti infrastrutturali

Assicurarsi che siano presenti i seguenti componenti e configurazioni:

* Server SAP HANA certificati e sistemi di storage NetApp .  Fare riferimento al https://www.sap.com/dmc/exp/2014-09-02-hana-hardware/enEN["Elenco hardware SAP HANA"^] per le opzioni disponibili:
* SUSE Linux Enterprise Server per applicazioni SAP 15 SP5/SP6 come host KVM
* Sistema di archiviazione NetApp ONTAP con Storage Virtual Machine (SVM) configurato per il traffico NFS e/o FCP
* Interfacce logiche (LIF) create sulle reti appropriate per il traffico NFS e FCP
* Schede di rete compatibili con SR-IOV (ad esempio, serie Mellanox ConnectX)
* Adattatori HBA Fibre Channel per l'accesso allo storage FCP
* Infrastruttura di rete che supporta le VLAN e i segmenti di rete richiesti
* VM configurata secondo la  https://documentation.suse.com/sbp/sap-15/html/SBP-SLES4SAP-HANAonKVM-SLES15SP7/["Best practice SUSE per SAP HANA su KVM"^]




== Considerazioni importanti

* SR-IOV deve essere utilizzato per la comunicazione di rete SAP HANA e per l'accesso allo storage tramite NFS, se possibile, ma è supportata anche la rete bridged. Ogni funzione virtuale (VF) assegnata a una VM richiede almeno 10 Gbit/s di larghezza di banda.
* Per utilizzare le LUN FCP, le porte HBA FCP fisiche devono essere assegnate alla VM come dispositivi PCI.  Una porta fisica può essere assegnata a una sola VM.
* I sistemi SAP HANA Multiple-Host non sono supportati in questa configurazione.




== Risorse aggiuntive

* Per le informazioni più aggiornate, inclusi l'architettura CPU supportata e le relative limitazioni, fai riferimento alla SAP Note https://me.sap.com/notes/3741904["3741904 - SAP HANA su SUSE KVM Virtualization con SLES 15 SP7 - SAP for Me"].
* Per informazioni sulla configurazione dei sistemi di archiviazione ONTAP , fare riferimento a https://docs.netapp.com/us-en/ontap["Documentazione ONTAP 9"] .
* Per la configurazione dello storage SAP HANA con i sistemi NetApp , fare riferimento a https://docs.netapp.com/us-en/netapp-solutions-sap/["Documentazione delle soluzioni SAP NetApp"] .




== Cosa succederà ora?

Dopo aver esaminato i requisiti di distribuzione,link:kvm-hana-network.html["configurare le interfacce di rete SR-IOV"] .
