---
sidebar: sidebar 
permalink: bp/saphana_aff_nfs_i_o_stack_configuration_for_sap_hana.html 
keywords: stack, configuration, io, i/o, optimal values 
summary: A partire da SAP HANA 1.0 SPS10, SAP ha introdotto i parametri per regolare il comportamento di i/o e ottimizzare il database per i file e i sistemi storage utilizzati. 
---
= Configurazione dello stack di i/o per SAP HANA
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
A partire da SAP HANA 1.0 SPS10, SAP ha introdotto i parametri per regolare il comportamento di i/o e ottimizzare il database per i file e i sistemi storage utilizzati.

NetApp ha condotto test delle performance per definire i valori ideali. La seguente tabella elenca i valori ottimali dedotti dai test delle prestazioni.

|===
| Parametro | Valore 


| max_parallel_io_requests | 128 


| async_read_submit | acceso 


| async_write_submit_active | acceso 


| async_write_submit_blocks | tutto 
|===
Per le versioni SAP HANA 1.0 fino a SPS12, questi parametri possono essere impostati durante l'installazione del database SAP HANA, come descritto nella nota SAP https://launchpad.support.sap.com/["2267798: Configurazione del database SAP HANA durante l'installazione con hdbparam"^].

In alternativa, è possibile impostare i parametri dopo l'installazione del database SAP HANA utilizzando `hdbparam` framework.

....
nf2adm@sapcc-hana-tst-06:/usr/sap/NF2/HDB00> hdbparam --paramset fileio.max_parallel_io_requests=128
nf2adm@sapcc-hana-tst-06:/usr/sap/NF2/HDB00> hdbparam --paramset fileio.async_write_submit_active=on
nf2adm@sapcc-hana-tst-06:/usr/sap/NF2/HDB00> hdbparam --paramset fileio.async_read_submit=on
nf2adm@sapcc-hana-tst-06:/usr/sap/NF2/HDB00> hdbparam --paramset fileio.async_write_submit_blocks=all
....
A partire da SAP HANA 2.0, `hdbparam` è stato obsoleto e i parametri sono stati spostati in `global.ini`. I parametri possono essere impostati utilizzando i comandi SQL o SAP HANA Studio. Per ulteriori informazioni, consulta la nota SAP https://launchpad.support.sap.com/["2399079: Eliminazione di hdbparam in HANA 2"^]. I parametri possono essere impostati anche all'interno del global.ini, come mostrato di seguito:

....
nf2adm@stlrx300s8-6: /usr/sap/NF2/SYS/global/hdb/custom/config> cat global.ini
…
[fileio]
async_read_submit = on
async_write_submit_active = on
max_parallel_io_requests = 128
async_write_submit_blocks = all
…
....
A partire da SAP HANA 2.0 SPS5, è possibile utilizzare `setParameter.py` script per impostare i parametri corretti:

....
nf2adm@sapcc-hana-tst-03:/usr/sap/NF2/HDB00/exe/python_support>
python setParameter.py -set=SYSTEM/global.ini/fileio/max_parallel_io_requests=128
python setParameter.py -set=SYSTEM/global.ini/fileio/async_read_submit=on
python setParameter.py -set=SYSTEM/global.ini/fileio/async_write_submit_active=on
python setParameter.py -set=SYSTEM/global.ini/fileio/async_write_submit_blocks=all
....