---
sidebar: sidebar 
permalink: lifecycle/sc-copy-clone-supported-infrastructure.html 
keywords: tr4667, 4667, SAP HANA, cloning, system refresh 
summary: 'Le soluzioni NetApp per l"ottimizzazione del Lifecycle management SAP sono integrate nel database SAP HANA e negli strumenti di Lifecycle management, combinando una data Protection integrata con l"efficiente applicazione con il provisioning flessibile dei sistemi di test SAP.' 
---
= Infrastruttura e scenari supportati
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Questo documento prende in esame gli scenari di refresh e cloning del sistema SAP per sistemi SAP HANA in esecuzione su sistemi NetApp on-premise, su Amazon FSX per sistemi NetApp ONTAP e su Azure NetApp Files. Tuttavia, non tutte le funzionalità e gli scenari sono disponibili su ogni piattaforma storage. La tabella seguente riassume le configurazioni supportate.

All'interno del documento, stiamo utilizzando un ambiente SAP HANA in esecuzione su sistemi NetApp on-premise con NFS come protocollo storage. La maggior parte dei passaggi del flusso di lavoro sono identici per le diverse piattaforme e, in caso di differenze, sono evidenziati in questo documento.

[cols="25%,25%,25%,25%"]
|===
|  | *Sistemi NetApp in loco* | *AWS FSX per NetApp ONTAP* | *Azure NetApp Files* 


| Protocollo di archiviazione e file system | Bare metal: NFS, FC con XFS VMware: NFS in-guest mounts, FC con VMDKs e XFS | NFS | NFS 


| Thin clone (FlexClone) | Sì | Sì | Sì, ma non integrato in SnapCenter 


| Operazione di suddivisione dei cloni | Sì | Sì | Sì, ma non integrato in SnapCenter 


| Clonazione dallo storage primario | Sì | Sì | Sì 


| Clonazione da backup off-site | Sì | Sì | Sì, ripristina su un nuovo volume dal backup ANF 


| Clonazione nel sito di DR | Sì | Sì | Sì, ma non integrato in SnapCenter 
|===
Ulteriori informazioni sulle operazioni di aggiornamento del sistema SAP per HANA con VMware VMFS e sistemi NetApp ASAr2 sono disponibili all'indirizzo  https://docs.netapp.com/us-en/netapp-solutions-sap/backup/hana-sc-vmfs-asar2sap-refresh.html["Aggiornamento del sistema SAP"].
