---
sidebar: sidebar 
permalink: lifecycle/sc-copy-clone-additional-info.html 
keywords: tr4667, 4667, SAP HANA, cloning, system refresh 
summary: 'Le soluzioni NetApp per l"ottimizzazione del Lifecycle management SAP sono integrate nel database SAP HANA e negli strumenti di Lifecycle management, combinando una data Protection integrata con l"efficiente applicazione con il provisioning flessibile dei sistemi di test SAP.' 
---
= Dove trovare informazioni aggiuntive e cronologia delle versioni
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Per ulteriori informazioni sulle informazioni descritte in questo documento, consultare i seguenti documenti e/o siti Web:

* link:../index.html["Soluzioni per applicazioni aziendali SAP e database SAP HANA (netapp.com)"]
* link:../backup/hana-sc-generic-scope.html["Backup e ripristino SAP HANA con SnapCenter"]
* link:../bp/hana-aff-fc-introduction.html["SAP HANA su NetApp All Flash FAS Systems con protocollo Fibre Channel"]
* link:../bp/hana-aff-nfs-introduction.html["SAP HANA su NetApp All Flash FAS Systems con NFS"]
* link:../backup/fsxn-overview.html["SAP HANA su Amazon FSX per NetApp ONTAP - Backup e recovery con SnapCenter"]
* link:lama-ansible-introduction.html["NetApp SAP Landscape Management Integration con Ansible"]
* link:libelle-sc-overview.html["Automazione delle operazioni di copia del sistema SAP con Libelle SystemCopy (netapp.com)"]
* link:../briefs/sap-alpaca-automation.html["Automazione di copia, refresh e cloning del sistema SAP dei workflow con ALPACA e NetApp SnapCenter"]
* link:../briefs/sap-avantra-automation.html["Automazione di copia, refresh e cloning dei flussi di lavoro del sistema SAP con Avantra e NetApp SnapCenter"]


[cols="21%,20%,59%"]
|===
| Versione | Data | Cronologia delle versioni del documento 


| Versione 1.0 | Febbraio 2018 | Release iniziale. 


| Versione 2.0 | Febbraio 2021  a| 
Riscrittura completa di SnapCenter 4.3 e script di automazione migliorati. + Nuova descrizione del workflow per il refresh di sistema e le operazioni dei cloni di sistema.



| Versione 3.0 | Maggio 2022 | Adattato al flusso di lavoro modificato con SnapCenter 4,6 P1 


| Versione 4.0 | Luglio 2024  a| 
Il documento riguarda i sistemi NetApp on-premise, FSX per ONTAP e Azure NetApp Files + nuove operazioni di SnapCenter 5,0 si montano e sbloccano durante la creazione e l'eliminazione dei cloni + aggiunta di istruzioni specifiche per Fibre Channel SAN + aggiunta di istruzioni specifiche per Azure NetApp Files + script adattato e semplificato `sc-system-refresh` + istruzioni incluse per SAP HANA abilitato crittografia dei volumi



| Versione 4.1 | Febbraio 2026 | Aggiunti i passaggi obbligatori per la crittografia HANA e SAP local secure store LSS 
|===